// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  GetApiAdminMarketingPoolsByIdPayoutsData,
  GetApiAdminMarketingPoolsByIdPayoutsResponses,
  GetApiAdminMarketingPoolsData,
  GetApiAdminMarketingPoolsResponses,
  GetApiAdminMarketingVideosData,
  GetApiAdminMarketingVideosResponses,
  GetApiAdminPostsData,
  GetApiAdminPostsResponses,
  GetApiAdminStatsData,
  GetApiAdminStatsResponses,
  GetApiAdminUsersData,
  GetApiAdminUsersResponses,
  PostApiAdminMarketingPoolsByIdCalculateData,
  PostApiAdminMarketingPoolsByIdCalculateErrors,
  PostApiAdminMarketingPoolsByIdCalculateResponses,
  PostApiAdminMarketingPoolsByIdPayData,
  PostApiAdminMarketingPoolsByIdPayErrors,
  PostApiAdminMarketingPoolsByIdPayResponses,
  PostApiAdminMarketingVideosByIdApproveData,
  PostApiAdminMarketingVideosByIdApproveErrors,
  PostApiAdminMarketingVideosByIdApproveResponses,
  PostApiAdminMarketingVideosByIdRejectData,
  PostApiAdminMarketingVideosByIdRejectResponses,
  PostApiAdminMarketingVideosByIdViewsData,
  PostApiAdminMarketingVideosByIdViewsErrors,
  PostApiAdminMarketingVideosByIdViewsResponses,
  PostApiAdminPostsByIdRemoveData,
  PostApiAdminPostsByIdRemoveErrors,
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRestoreData,
  PostApiAdminPostsByIdRestoreErrors,
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminUsersByIdSuspendData,
  PostApiAdminUsersByIdSuspendErrors,
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdUnsuspendData,
  PostApiAdminUsersByIdUnsuspendErrors,
  PostApiAdminUsersByIdUnsuspendResponses,
  PutApiAdminMarketingPoolsData,
  PutApiAdminMarketingPoolsErrors,
  PutApiAdminMarketingPoolsResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Search users by username or email
 */
export const getApiAdminUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminUsersData, ThrowOnError>,
): RequestResult<GetApiAdminUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminUsersResponses, unknown, ThrowOnError>({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/users",
    ...options,
  })

/**
 * Suspend a user site-wide
 */
export const postApiAdminUsersByIdSuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdSuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdSuspendResponses,
  PostApiAdminUsersByIdSuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdSuspendResponses,
    PostApiAdminUsersByIdSuspendErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/users/{id}/suspend",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Lift a user's suspension
 */
export const postApiAdminUsersByIdUnsuspend = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminUsersByIdUnsuspendData, ThrowOnError>,
): RequestResult<
  PostApiAdminUsersByIdUnsuspendResponses,
  PostApiAdminUsersByIdUnsuspendErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminUsersByIdUnsuspendResponses,
    PostApiAdminUsersByIdUnsuspendErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/users/{id}/unsuspend",
    ...options,
  })

/**
 * Search posts by title (includes removed posts)
 */
export const getApiAdminPosts = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminPostsData, ThrowOnError>,
): RequestResult<GetApiAdminPostsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminPostsResponses, unknown, ThrowOnError>({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/posts",
    ...options,
  })

/**
 * Remove a post site-wide (admin)
 */
export const postApiAdminPostsByIdRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRemoveData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRemoveResponses,
  PostApiAdminPostsByIdRemoveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRemoveResponses,
    PostApiAdminPostsByIdRemoveErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/posts/{id}/remove",
    ...options,
  })

/**
 * Restore a removed post site-wide (admin)
 */
export const postApiAdminPostsByIdRestore = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminPostsByIdRestoreData, ThrowOnError>,
): RequestResult<
  PostApiAdminPostsByIdRestoreResponses,
  PostApiAdminPostsByIdRestoreErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminPostsByIdRestoreResponses,
    PostApiAdminPostsByIdRestoreErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/posts/{id}/restore",
    ...options,
  })

/**
 * Site-wide counts overview
 */
export const getApiAdminStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminStatsData, ThrowOnError>,
): RequestResult<GetApiAdminStatsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminStatsResponses, unknown, ThrowOnError>({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/stats",
    ...options,
  })

/**
 * The video review queue
 */
export const getApiAdminMarketingVideos = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAdminMarketingVideosData, ThrowOnError>,
): RequestResult<GetApiAdminMarketingVideosResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiAdminMarketingVideosResponses, unknown, ThrowOnError>({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/videos",
    ...options,
  })

/**
 * Approves a video and starts its 30-day counting window
 */
export const postApiAdminMarketingVideosByIdApprove = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminMarketingVideosByIdApproveData, ThrowOnError>,
): RequestResult<
  PostApiAdminMarketingVideosByIdApproveResponses,
  PostApiAdminMarketingVideosByIdApproveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminMarketingVideosByIdApproveResponses,
    PostApiAdminMarketingVideosByIdApproveErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/videos/{id}/approve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Rejects a video, with a reason the submitter will see
 */
export const postApiAdminMarketingVideosByIdReject = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminMarketingVideosByIdRejectData, ThrowOnError>,
): RequestResult<PostApiAdminMarketingVideosByIdRejectResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiAdminMarketingVideosByIdRejectResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/videos/{id}/reject",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Records the view count read at the 30-day mark
 */
export const postApiAdminMarketingVideosByIdViews = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminMarketingVideosByIdViewsData, ThrowOnError>,
): RequestResult<
  PostApiAdminMarketingVideosByIdViewsResponses,
  PostApiAdminMarketingVideosByIdViewsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminMarketingVideosByIdViewsResponses,
    PostApiAdminMarketingVideosByIdViewsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/videos/{id}/views",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Every business's pool for a month, with the 20% suggestion
 */
export const getApiAdminMarketingPools = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminMarketingPoolsData, ThrowOnError>,
): RequestResult<GetApiAdminMarketingPoolsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetApiAdminMarketingPoolsResponses, unknown, ThrowOnError>({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/pools",
    ...options,
  })

/**
 * Sets the dollar pool a business will pay out for a month
 */
export const putApiAdminMarketingPools = <ThrowOnError extends boolean = false>(
  options?: Options<PutApiAdminMarketingPoolsData, ThrowOnError>,
): RequestResult<
  PutApiAdminMarketingPoolsResponses,
  PutApiAdminMarketingPoolsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).put<
    PutApiAdminMarketingPoolsResponses,
    PutApiAdminMarketingPoolsErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/pools",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Splits the pool between the month's eligible videos
 */
export const postApiAdminMarketingPoolsByIdCalculate = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminMarketingPoolsByIdCalculateData, ThrowOnError>,
): RequestResult<
  PostApiAdminMarketingPoolsByIdCalculateResponses,
  PostApiAdminMarketingPoolsByIdCalculateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminMarketingPoolsByIdCalculateResponses,
    PostApiAdminMarketingPoolsByIdCalculateErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/pools/{id}/calculate",
    ...options,
  })

/**
 * The calculated payouts for a pool
 */
export const getApiAdminMarketingPoolsByIdPayouts = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAdminMarketingPoolsByIdPayoutsData, ThrowOnError>,
): RequestResult<GetApiAdminMarketingPoolsByIdPayoutsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetApiAdminMarketingPoolsByIdPayoutsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/pools/{id}/payouts",
    ...options,
  })

/**
 * Sends every pending payout in the pool through Stripe
 */
export const postApiAdminMarketingPoolsByIdPay = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAdminMarketingPoolsByIdPayData, ThrowOnError>,
): RequestResult<
  PostApiAdminMarketingPoolsByIdPayResponses,
  PostApiAdminMarketingPoolsByIdPayErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAdminMarketingPoolsByIdPayResponses,
    PostApiAdminMarketingPoolsByIdPayErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      {
        in: "cookie",
        name: "sproutbiz_session",
        type: "apiKey",
      },
    ],
    url: "/api/admin/marketing/pools/{id}/pay",
    ...options,
  })
