// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {})
}

export type InnerErrorT = {
  code: string
  innererror?: InnerErrorT
}

export type ErrorObjectT = {
  code:
    | "BadRequest"
    | "Unauthenticated"
    | "Unauthorized"
    | "Forbidden"
    | "NotFound"
    | "MethodNotAllowed"
    | "Conflict"
    | "UnprocessableEntity"
    | "TooManyRequests"
    | "InternalServerError"
    | "ServiceUnavailable"
    | "InsufficientPermissions"
    | "Suspended"
    | "ValidationFailed"
    | "InvalidInput"
    | "MissingRequiredField"
    | "ResourceNotFound"
    | "ResourceAlreadyExists"
    | "ResourceLocked"
    | "OperationFailed"
    | "DataIntegrityViolation"
    | "RateLimitExceeded"
    | string
  message: string
  target?: string
  details?: Array<ErrorObjectT>
  innererror?: InnerErrorT
}

export type ErrorResponseT = {
  error: ErrorObjectT
}

export type GetApiAdminUsersData = {
  body?: never
  path?: never
  query?: {
    q?: string
    cursor?: string
  }
  url: "/api/admin/users"
}

export type GetApiAdminUsersResponses = {
  /**
   * Matching users
   */
  200: {
    data: Array<{
      id: string
      username: string
      email: string
      postKarma: number
      commentKarma: number
      createdAt: Date
      suspendedAt: Date | null
      suspensionReason: string | null
    }>
    nextCursor: string | null
  }
}

export type GetApiAdminUsersResponse = GetApiAdminUsersResponses[keyof GetApiAdminUsersResponses]

export type PostApiAdminUsersByIdSuspendData = {
  body?: {
    reason: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/suspend"
}

export type PostApiAdminUsersByIdSuspendErrors = {
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdSuspendError =
  PostApiAdminUsersByIdSuspendErrors[keyof PostApiAdminUsersByIdSuspendErrors]

export type PostApiAdminUsersByIdSuspendResponses = {
  /**
   * User suspended
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminUsersByIdSuspendResponse =
  PostApiAdminUsersByIdSuspendResponses[keyof PostApiAdminUsersByIdSuspendResponses]

export type PostApiAdminUsersByIdUnsuspendData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/users/{id}/unsuspend"
}

export type PostApiAdminUsersByIdUnsuspendErrors = {
  /**
   * User not found
   */
  404: ErrorResponseT
}

export type PostApiAdminUsersByIdUnsuspendError =
  PostApiAdminUsersByIdUnsuspendErrors[keyof PostApiAdminUsersByIdUnsuspendErrors]

export type PostApiAdminUsersByIdUnsuspendResponses = {
  /**
   * User unsuspended
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminUsersByIdUnsuspendResponse =
  PostApiAdminUsersByIdUnsuspendResponses[keyof PostApiAdminUsersByIdUnsuspendResponses]

export type GetApiAdminPostsData = {
  body?: never
  path?: never
  query?: {
    q?: string
    cursor?: string
  }
  url: "/api/admin/posts"
}

export type GetApiAdminPostsResponses = {
  /**
   * Matching posts
   */
  200: {
    data: Array<{
      id: string
      title: string
      communityId: string | null
      communityName: string | null
      authorUsername: string | null
      score: number
      removedAt: Date | null
      createdAt: Date
    }>
    nextCursor: string | null
  }
}

export type GetApiAdminPostsResponse = GetApiAdminPostsResponses[keyof GetApiAdminPostsResponses]

export type PostApiAdminPostsByIdRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/posts/{id}/remove"
}

export type PostApiAdminPostsByIdRemoveErrors = {
  /**
   * Post not found
   */
  404: ErrorResponseT
}

export type PostApiAdminPostsByIdRemoveError =
  PostApiAdminPostsByIdRemoveErrors[keyof PostApiAdminPostsByIdRemoveErrors]

export type PostApiAdminPostsByIdRemoveResponses = {
  /**
   * Post removed
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminPostsByIdRemoveResponse =
  PostApiAdminPostsByIdRemoveResponses[keyof PostApiAdminPostsByIdRemoveResponses]

export type PostApiAdminPostsByIdRestoreData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/posts/{id}/restore"
}

export type PostApiAdminPostsByIdRestoreErrors = {
  /**
   * Post not found
   */
  404: ErrorResponseT
}

export type PostApiAdminPostsByIdRestoreError =
  PostApiAdminPostsByIdRestoreErrors[keyof PostApiAdminPostsByIdRestoreErrors]

export type PostApiAdminPostsByIdRestoreResponses = {
  /**
   * Post restored
   */
  200: {
    [key: string]: unknown
  }
}

export type PostApiAdminPostsByIdRestoreResponse =
  PostApiAdminPostsByIdRestoreResponses[keyof PostApiAdminPostsByIdRestoreResponses]

export type GetApiAdminStatsData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/stats"
}

export type GetApiAdminStatsResponses = {
  /**
   * Counts
   */
  200: {
    users: number
    posts: number
    communities: number
    comments: number
    reportsPending: number
  }
}

export type GetApiAdminStatsResponse = GetApiAdminStatsResponses[keyof GetApiAdminStatsResponses]

export type GetApiAdminMarketingVideosData = {
  body?: never
  path?: never
  query?: {
    status?: "pending" | "approved" | "rejected" | "measured" | "paid"
  }
  url: "/api/admin/marketing/videos"
}

export type GetApiAdminMarketingVideosResponses = {
  /**
   * Videos
   */
  200: {
    data: Array<{
      id: string
      businessId: string
      businessName: string
      businessSlug: string
      submitterUserId: string
      submitterUsername: string
      platform: string
      platformLabel: string
      url: string
      status: string
      rejectionReason: string | null
      durationSeconds: number | null
      postedAt: string | null
      measureAt: string | null
      viewCount: number | null
      weightedViews: number | null
      minViews: number
      meetsMinimum: boolean
      submittedAt: string
    }>
  }
}

export type GetApiAdminMarketingVideosResponse =
  GetApiAdminMarketingVideosResponses[keyof GetApiAdminMarketingVideosResponses]

export type PostApiAdminMarketingVideosByIdApproveData = {
  body?: {
    postedAt: Date
    durationSeconds: number
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/videos/{id}/approve"
}

export type PostApiAdminMarketingVideosByIdApproveErrors = {
  /**
   * Too short, or already reviewed
   */
  400: ErrorResponseT
}

export type PostApiAdminMarketingVideosByIdApproveError =
  PostApiAdminMarketingVideosByIdApproveErrors[keyof PostApiAdminMarketingVideosByIdApproveErrors]

export type PostApiAdminMarketingVideosByIdApproveResponses = {
  /**
   * Approved
   */
  200: {
    data: {
      id: string
      businessId: string
      businessName: string
      businessSlug: string
      submitterUserId: string
      submitterUsername: string
      platform: string
      platformLabel: string
      url: string
      status: string
      rejectionReason: string | null
      durationSeconds: number | null
      postedAt: string | null
      measureAt: string | null
      viewCount: number | null
      weightedViews: number | null
      minViews: number
      meetsMinimum: boolean
      submittedAt: string
    }
  }
}

export type PostApiAdminMarketingVideosByIdApproveResponse =
  PostApiAdminMarketingVideosByIdApproveResponses[keyof PostApiAdminMarketingVideosByIdApproveResponses]

export type PostApiAdminMarketingVideosByIdRejectData = {
  body?: {
    reason: string
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/videos/{id}/reject"
}

export type PostApiAdminMarketingVideosByIdRejectResponses = {
  /**
   * Rejected
   */
  200: {
    data: {
      id: string
      businessId: string
      businessName: string
      businessSlug: string
      submitterUserId: string
      submitterUsername: string
      platform: string
      platformLabel: string
      url: string
      status: string
      rejectionReason: string | null
      durationSeconds: number | null
      postedAt: string | null
      measureAt: string | null
      viewCount: number | null
      weightedViews: number | null
      minViews: number
      meetsMinimum: boolean
      submittedAt: string
    }
  }
}

export type PostApiAdminMarketingVideosByIdRejectResponse =
  PostApiAdminMarketingVideosByIdRejectResponses[keyof PostApiAdminMarketingVideosByIdRejectResponses]

export type PostApiAdminMarketingVideosByIdViewsData = {
  body?: {
    viewCount: number
  }
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/videos/{id}/views"
}

export type PostApiAdminMarketingVideosByIdViewsErrors = {
  /**
   * Not an approved video, or an unknown platform
   */
  400: ErrorResponseT
}

export type PostApiAdminMarketingVideosByIdViewsError =
  PostApiAdminMarketingVideosByIdViewsErrors[keyof PostApiAdminMarketingVideosByIdViewsErrors]

export type PostApiAdminMarketingVideosByIdViewsResponses = {
  /**
   * Recorded
   */
  200: {
    data: {
      id: string
      businessId: string
      businessName: string
      businessSlug: string
      submitterUserId: string
      submitterUsername: string
      platform: string
      platformLabel: string
      url: string
      status: string
      rejectionReason: string | null
      durationSeconds: number | null
      postedAt: string | null
      measureAt: string | null
      viewCount: number | null
      weightedViews: number | null
      minViews: number
      meetsMinimum: boolean
      submittedAt: string
    }
  }
}

export type PostApiAdminMarketingVideosByIdViewsResponse =
  PostApiAdminMarketingVideosByIdViewsResponses[keyof PostApiAdminMarketingVideosByIdViewsResponses]

export type GetApiAdminMarketingPoolsData = {
  body?: never
  path?: never
  query: {
    month: string
  }
  url: "/api/admin/marketing/pools"
}

export type GetApiAdminMarketingPoolsResponses = {
  /**
   * Pools
   */
  200: {
    data: Array<{
      businessId: string
      businessName: string
      businessSlug: string
      month: string
      poolId: string | null
      revenueUsdCents: number
      costUsdCents: number
      netUsdCents: number
      suggestedUsdCents: number
      poolUsdCents: number
      notes: string | null
      status: string
      eligibleVideoCount: number
      totalWeightedViews: number
    }>
  }
}

export type GetApiAdminMarketingPoolsResponse =
  GetApiAdminMarketingPoolsResponses[keyof GetApiAdminMarketingPoolsResponses]

export type PutApiAdminMarketingPoolsData = {
  body?: {
    businessId: string
    month: string
    poolUsdCents: number
    notes?: string | null
  }
  path?: never
  query?: never
  url: "/api/admin/marketing/pools"
}

export type PutApiAdminMarketingPoolsErrors = {
  /**
   * The pool has already been paid
   */
  400: ErrorResponseT
}

export type PutApiAdminMarketingPoolsError =
  PutApiAdminMarketingPoolsErrors[keyof PutApiAdminMarketingPoolsErrors]

export type PutApiAdminMarketingPoolsResponses = {
  /**
   * Pool saved
   */
  200: {
    poolId: string
    poolUsdCents: number
    status: string
    data: Array<{
      id: string
      videoId: string
      username: string
      platform: string
      url: string
      viewCount: number | null
      weightedViews: number
      shareBp: number
      grossUsdCents: number
      feeUsdCents: number
      netUsdCents: number
      status: string
      failureReason: string | null
      paidAt: string | null
      payable: boolean
    }>
  }
}

export type PutApiAdminMarketingPoolsResponse =
  PutApiAdminMarketingPoolsResponses[keyof PutApiAdminMarketingPoolsResponses]

export type PostApiAdminMarketingPoolsByIdCalculateData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/pools/{id}/calculate"
}

export type PostApiAdminMarketingPoolsByIdCalculateErrors = {
  /**
   * The pool has already been paid
   */
  400: ErrorResponseT
}

export type PostApiAdminMarketingPoolsByIdCalculateError =
  PostApiAdminMarketingPoolsByIdCalculateErrors[keyof PostApiAdminMarketingPoolsByIdCalculateErrors]

export type PostApiAdminMarketingPoolsByIdCalculateResponses = {
  /**
   * Calculated
   */
  200: {
    poolId: string
    poolUsdCents: number
    status: string
    data: Array<{
      id: string
      videoId: string
      username: string
      platform: string
      url: string
      viewCount: number | null
      weightedViews: number
      shareBp: number
      grossUsdCents: number
      feeUsdCents: number
      netUsdCents: number
      status: string
      failureReason: string | null
      paidAt: string | null
      payable: boolean
    }>
  }
}

export type PostApiAdminMarketingPoolsByIdCalculateResponse =
  PostApiAdminMarketingPoolsByIdCalculateResponses[keyof PostApiAdminMarketingPoolsByIdCalculateResponses]

export type GetApiAdminMarketingPoolsByIdPayoutsData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/pools/{id}/payouts"
}

export type GetApiAdminMarketingPoolsByIdPayoutsResponses = {
  /**
   * Payouts
   */
  200: {
    poolId: string
    poolUsdCents: number
    status: string
    data: Array<{
      id: string
      videoId: string
      username: string
      platform: string
      url: string
      viewCount: number | null
      weightedViews: number
      shareBp: number
      grossUsdCents: number
      feeUsdCents: number
      netUsdCents: number
      status: string
      failureReason: string | null
      paidAt: string | null
      payable: boolean
    }>
  }
}

export type GetApiAdminMarketingPoolsByIdPayoutsResponse =
  GetApiAdminMarketingPoolsByIdPayoutsResponses[keyof GetApiAdminMarketingPoolsByIdPayoutsResponses]

export type PostApiAdminMarketingPoolsByIdPayData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/admin/marketing/pools/{id}/pay"
}

export type PostApiAdminMarketingPoolsByIdPayErrors = {
  /**
   * Payouts are not configured on this deployment
   */
  503: ErrorResponseT
}

export type PostApiAdminMarketingPoolsByIdPayError =
  PostApiAdminMarketingPoolsByIdPayErrors[keyof PostApiAdminMarketingPoolsByIdPayErrors]

export type PostApiAdminMarketingPoolsByIdPayResponses = {
  /**
   * Payouts attempted
   */
  200: {
    poolId: string
    poolUsdCents: number
    status: string
    data: Array<{
      id: string
      videoId: string
      username: string
      platform: string
      url: string
      viewCount: number | null
      weightedViews: number
      shareBp: number
      grossUsdCents: number
      feeUsdCents: number
      netUsdCents: number
      status: string
      failureReason: string | null
      paidAt: string | null
      payable: boolean
    }>
  }
}

export type PostApiAdminMarketingPoolsByIdPayResponse =
  PostApiAdminMarketingPoolsByIdPayResponses[keyof PostApiAdminMarketingPoolsByIdPayResponses]
